<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0).
 *
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateVocabulariesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $connection = config('trans-helper.database.connection') ?: config('database.default');
        if (!Schema::connection($connection)->hasTable('_trans_helper_cites')) {
            Schema::connection($connection)->create(
                '_trans_helper_cites',
                function (Blueprint $table) {
                    $table->bigIncrements('id');
                    $table->string('file', 256)->default('');
                    $table->unsignedBigInteger('line');
                    $table->string('class', 256)->nullable();
                    $table->string('function', 256)->nullable();
                    $table->mediumText('code')->nullable();
                    $table->timestamps();

                    $table->index('created_at', 'created_at');
                    $table->index('updated_at', 'updated_at');
                    $table->index('function', 'function');
                    $table->index('file', 'file');
                    $table->index('line', 'line');
                    $table->index('class', 'class');
                }
            );
        }

        if (!Schema::connection($connection)->hasTable('_trans_helper_terms')) {
            Schema::connection($connection)->create(
                '_trans_helper_terms',
                function (Blueprint $table) {
                    $table->bigIncrements('id');
                    $table->string('namespace', 256)->default('');
                    $table->string('term', 256)->default('');
                    $table->json('translation')->nullable();
                    $table->timestamps();

                    $table->unique(['namespace', 'term'], 'unique_namespace_term');
                    $table->index('namespace', 'namespace');
                    $table->index('term', 'term');
                    $table->index('created_at', 'created_at');
                    $table->index('updated_at', 'updated_at');
                }
            );
        }

        if (!Schema::connection($connection)->hasTable('_trans_helper_links')) {
            Schema::connection($connection)->create(
                '_trans_helper_links',
                function (Blueprint $table) {
                    $table->unsignedBigInteger('cited');
                    $table->unsignedBigInteger('vocab');

                    $table->primary(['cited', 'vocab']);
                    $table->index('cited', 'cited');
                    $table->index('vocab', 'vocab');
                    $table->foreign('cited')
                        ->references('id')
                        ->on('_trans_helper_cites')
                        ->onDelete('cascade');
                    $table->foreign('vocab')
                        ->references('id')
                        ->on('_trans_helper_terms')
                        ->onDelete('cascade');
                }
            );
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $connection = config('trans-helper.database.connection') ?: config('database.default');
        Schema::connection($connection)->dropIfExists('_trans_helper_links');
        Schema::connection($connection)->dropIfExists('_trans_helper_cites');
        Schema::connection($connection)->dropIfExists('_trans_helper_terms');
    }
}
